version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rayuela-frontend
    restart: unless-stopped
    networks:
      - rayuela_net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-frontend
    restart: unless-stopped
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl_params.conf:/etc/nginx/snippets/ssl_params.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - frontend_build:/usr/share/nginx/html:ro
    networks:
      - rayuela_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command: >
      -c "trap exit TERM;
          while :; do
            certbot renew --webroot -w /var/www/certbot --quiet;
            sleep 12h;
          done"

volumes:
  frontend_build:

networks:
  rayuela_net:
    external: true
    name: rayuela_net
